import {
  getbunny,
  getcat,
  getdog,
  getduck,
  getelephant,
  getfox,
  getkoala,
  getpanda,
} from '../Utils/animalAPI';

export const numbers = [
  {value: 0, tr: 'sıfır', en: 'zero'},
  {value: 1, tr: 'bir', en: 'one'},
  {value: 2, tr: 'iki', en: 'two'},
  {value: 3, tr: 'üç', en: 'three'},
  {value: 4, tr: 'dört', en: 'four'},
  {value: 5, tr: 'beş', en: 'five'},
  {value: 6, tr: 'altı', en: 'six'},
  {value: 7, tr: 'yedi', en: 'seven'},
  {value: 8, tr: 'sekiz', en: 'eight'},
  {value: 9, tr: 'dokuz', en: 'nine'},
  {value: 10, tr: 'on', en: 'ten'},
  {value: 11, tr: 'on bir', en: 'eleven'},
  {value: 12, tr: 'on iki', en: 'twelve'},
  {value: 13, tr: 'on üç', en: 'thirteen'},
  {value: 14, tr: 'on dört', en: 'fourteen'},
  {value: 15, tr: 'on beş', en: 'fifteen'},
  {value: 16, tr: 'on altı', en: 'sixteen'},
  {value: 17, tr: 'on yedi', en: 'seventeen'},
  {value: 18, tr: 'on sekiz', en: 'eighteen'},
  {value: 19, tr: 'on dokuz', en: 'nineteen'},
  {value: 20, tr: 'yirmi', en: 'twenty'},
  {value: 21, tr: 'yirmi bir', en: 'twenty one'},
  {value: 22, tr: 'yirmi iki', en: 'twenty two'},
  {value: 23, tr: 'yirmi üç', en: 'twenty three'},
  {value: 24, tr: 'yirmi dört', en: 'twenty four'},
  {value: 25, tr: 'yirmi beş', en: 'twenty five'},
  {value: 26, tr: 'yirmi altı', en: 'twenty six'},
  {value: 27, tr: 'yirmi yedi', en: 'twenty seven'},
  {value: 28, tr: 'yirmi sekiz', en: 'twenty eight'},
  {value: 29, tr: 'yirmi dokuz', en: 'twenty nine'},
  {value: 30, tr: 'otuz', en: 'thirty'},
  {value: 31, tr: 'otuz bir', en: 'thirty one'},
  {value: 32, tr: 'otuz iki', en: 'thirty two'},
  {value: 33, tr: 'otuz üç', en: 'thirty three'},
  {value: 34, tr: 'otuz dört', en: 'thirty four'},
  {value: 35, tr: 'otuz beş', en: 'thirty five'},
  {value: 36, tr: 'otuz altı', en: 'thirty six'},
  {value: 37, tr: 'otuz yedi', en: 'thirty seven'},
  {value: 38, tr: 'otuz sekiz', en: 'thirty eight'},
  {value: 39, tr: 'otuz dokuz', en: 'thirty nine'},
  {value: 40, tr: 'kırk', en: 'forty'},
  {value: 41, tr: 'kırk bir', en: 'forty one'},
  {value: 42, tr: 'kırk iki', en: 'forty two'},
  {value: 43, tr: 'kırk üç', en: 'forty three'},
  {value: 44, tr: 'kırk dört', en: 'forty four'},
  {value: 45, tr: 'kırk beş', en: 'forty five'},
  {value: 46, tr: 'kırk altı', en: 'forty six'},
  {value: 47, tr: 'kırk yedi', en: 'forty seven'},
  {value: 48, tr: 'kırk sekiz', en: 'forty eight'},
  {value: 49, tr: 'kırk dokuz', en: 'forty nine'},
  {value: 50, tr: 'elli', en: 'fifty'},
  {value: 51, tr: 'elli bir', en: 'fifty one'},
  {value: 52, tr: 'elli iki', en: 'fifty two'},
  {value: 53, tr: 'elli üç', en: 'fifty three'},
  {value: 54, tr: 'elli dört', en: 'fifty four'},
  {value: 55, tr: 'elli beş', en: 'fifty five'},
  {value: 56, tr: 'elli altı', en: 'fifty six'},
  {value: 57, tr: 'elli yedi', en: 'fifty seven'},
  {value: 58, tr: 'elli sekiz', en: 'fifty eight'},
  {value: 59, tr: 'elli dokuz', en: 'fifty nine'},
  {value: 60, tr: 'altmış', en: 'sixty'},
  {value: 61, tr: 'altmış bir', en: 'sixty one'},
  {value: 62, tr: 'altmış iki', en: 'sixty two'},
  {value: 63, tr: 'altmış üç', en: 'sixty three'},
  {value: 64, tr: 'altmış dört', en: 'sixty four'},
  {value: 65, tr: 'altmış beş', en: 'sixty five'},
  {value: 66, tr: 'altmış altı', en: 'sixty six'},
  {value: 67, tr: 'altmış yedi', en: 'sixty seven'},
  {value: 68, tr: 'altmış sekiz', en: 'sixty eight'},
  {value: 69, tr: 'altmış dokuz', en: 'sixty nine'},
  {value: 70, tr: 'yetmiş', en: 'seventy'},
  {value: 71, tr: 'yetmiş bir', en: 'seventy one'},
  {value: 72, tr: 'yetmiş iki', en: 'seventy two'},
  {value: 73, tr: 'yetmiş üç', en: 'seventy three'},
  {value: 74, tr: 'yetmiş dört', en: 'seventy four'},
  {value: 75, tr: 'yetmiş beş', en: 'seventy five'},
  {value: 76, tr: 'yetmiş altı', en: 'seventy six'},
  {value: 77, tr: 'yetmiş yedi', en: 'seventy seven'},
  {value: 78, tr: 'yetmiş sekiz', en: 'seventy eight'},
  {value: 79, tr: 'yetmiş dokuz', en: 'seventy nine'},
  {value: 80, tr: 'seksen', en: 'eighty'},
  {value: 81, tr: 'seksen bir', en: 'eighty one'},
  {value: 82, tr: 'seksen iki', en: 'eighty two'},
  {value: 83, tr: 'seksen üç', en: 'eighty three'},
  {value: 84, tr: 'seksen dört', en: 'eighty four'},
  {value: 85, tr: 'seksen beş', en: 'eighty five'},
  {value: 86, tr: 'seksen altı', en: 'eighty six'},
  {value: 87, tr: 'seksen yedi', en: 'eighty seven'},
  {value: 88, tr: 'seksen sekiz', en: 'eighty eight'},
  {value: 89, tr: 'seksen dokuz', en: 'eighty nine'},
  {value: 90, tr: 'doksan', en: 'ninety'},
  {value: 91, tr: 'doksan bir', en: 'ninety one '},
  {value: 92, tr: 'doksan iki', en: 'ninety two'},
  {value: 93, tr: 'doksan üç', en: 'ninety three'},
  {value: 94, tr: 'doksan dört', en: 'ninety four'},
  {value: 95, tr: 'doksan beş', en: 'ninety five'},
  {value: 96, tr: 'doksan altı', en: 'ninety six'},
  {value: 97, tr: 'doksan yedi', en: 'ninety seven'},
  {value: 98, tr: 'doksan sekiz', en: 'ninety eight'},
  {value: 99, tr: 'doksan dokuz', en: 'ninety nine'},
  {value: 100, tr: 'yüz', en: 'one hundred'},
];
export const animals = [
  {value: 'elephant', tr: 'fil', en: 'elephant', url: getelephant},
  {value: 'dog', tr: 'köpek', en: 'dog', url: getdog},
  {value: 'cat', tr: 'kedi', en: 'cat', url: getcat},
  {value: 'bunny', tr: 'tavşan', en: 'bunny', url: getbunny},
  {value: 'duck', tr: 'ördek', en: 'duck', url: getduck},
  {value: 'fox', tr: 'tilki', en: 'fox', url: getfox},
  {value: 'koala', tr: 'koala', en: 'koala', url: getkoala},
  {value: 'panda', tr: 'panda', en: 'panda', url: getpanda},
];
export const colors = [
  {value: 'red', tr: 'kırmızı', en: 'red'},
  {value: 'blue', tr: 'mavi', en: 'blue'},
  {value: 'green', tr: 'yeşil', en: 'green'},
  {value: 'purple', tr: 'mor', en: 'purple'},
  {value: 'yellow', tr: 'sarı', en: 'yellow'},
  {value: 'white', tr: 'beyaz', en: 'white'},
  {value: 'black', tr: 'siyah', en: 'black'},
  {value: 'orange', tr: 'turuncu', en: 'orange'},
  {value: 'pink', tr: 'pembe', en: 'pink'},
  {value: 'turquoise', tr: 'turkuaz', en: 'turquoise'},
  {value: 'grey', tr: 'gri', en: 'grey'},
];
export const objects = [
  {value: 'table', tr: 'masa', en: 'table'},
  {value: 'chair', tr: 'sandalye', en: 'chair'},
  {value: 'sofa', tr: 'koltuk', en: 'sofa'},
  {value: 'plate', tr: 'tabak', en: 'plate'},
  {value: 'fork', tr: 'çatal', en: 'fork'},
  {value: 'spoon', tr: 'kaşık', en: 'spoon'},
  {value: 'bowl', tr: 'kase', en: 'bowl'},
  {value: 'pillow', tr: 'yastık', en: 'pillow'},
  {value: 'bed', tr: 'yatak', en: 'bed'},
];
